### ISSUE TITLE
Possibility of adding permit_all_actions_except and forbid_all_actions_except

### ISSUE THREAD

**Issue by jacobperia** [pundit-community/pundit-matchers#146]
Thanks for all the work guys!!

I'm proposing to add something i thought would be very useful, along the lines of:
`it { is_expected.to permit_all_actions_except([:action_1, : action_2]) }`
and 
`it { is_expected.to forbid_all_actions_except([:action_1, : action_2]) }`

For example, i'm permitting more than 20 actions and a single forbidden action. This would then need 2 lines of code preventing me from using the very simple `permit_all_actions` method:
```
it { is_expected.to permit_actions([:action_1,.....:action_20]) }
it { is_expected.to forbid_action(:forbidden_action) }
```

With my proposal, you can just list a few actions in the **except** list.

**Comment by chrisalley** [comment]
We could shorten the matcher names to:

`it { is_expected.to permit_actions_except([:action_1, :action_2]) }`
`it { is_expected.to forbid_actions_except([:action_1, :action_2]) }`

Do you have any thoughts on this proposal, @tagliala?

**Comment by tagliala** [comment]
I would leave `all` because it is more explicit. I think this can be useful in some scenarios. There are some situations where I would need this but it would require some effort

- does not qualify for a negation (not to permit all actions except)
- should check for both permit and forbid at the same time

**Comment by chrisalley** [comment]
I'm happy for us to proceed with the `permit_all_actions_except` and `forbid_all_actions_except` syntax and for you to lead the implementation @tagliala (if you want to).

**Comment by tagliala** [comment]
Let me see if it is better to add an `except` parameter to `permit_all`

**Comment by tagliala** [comment]
First findings:

### 1. This will introduce some ambiguity

Actions: `x, y, z`
Permit all actions except `z` does it mean that:

A. `z` is forbidden
B. `z` is not going to be checked

### 2. Complex error message

Permit/Forbid all actions message is quite simple, but now we should introduce a "conditional failure" because the failure may happen in the exception, if they should be checked to be true, so we have something like

```rb
message = +"expected '#{policy_info}' to permit all actions"
message <<
  if excluded_actions.present?
    "except #{excluded_actions}"
  else
    ','
  end
message << " but forbade #{policy_info.forbidden_actions}" # not sure, the failure may be that the "except action" should be permitted
message << user_message
```

### Conclusion

We are doing our best to avoid ambiguity and this option will introduce new ambiguity. I would reconsider and provide the list of actions and go for `permit only`

**Comment by chrisalley** [comment]
> A. z is forbidden
> B. z is not going to be checked
>
> Maybe the desired behaviour is A, which is also safer, but B is not wrong

A is probably what the spec writer wants, e.g.

* to check that all of the actions are permitted, except for a small set of actions that the user cannot perform (e.g. delete).
* to check that all of the actions are forbidden, except for a small set of actions that the user can perform (e.g. view).

However, as you pointed out, it is ambiguous.

> We are doing our best to avoid ambiguity and this option will introduce new ambiguity. I would reconsider and provide the list of actions and go for `permit only`

Are you suggesting we should just stay with the status quo and use the `permit_only_actions` / `forbid_only_actions` matchers?

E.g. instead of 

`permit_all_actions_except(:destroy)`

we write

```ruby
forbid_only_actions(:destroy)
permit_actions(:index, :show, :new, :edit, :create, :update) # List other actions here
```

The main downside is that the latter list must be manually constructed. I wonder then, if we should use a composite matcher to permit the remaining actions without manually specifying the list? E.g.

```ruby
# Permit all actions except destroy:
forbid_only_actions(:destroy).permitting_other_actions

# Forbid all actions except show:
permit_only_actions(:show).forbidding_other_actions
```

**Comment by tagliala** [comment]
Sorry for the late reply, I've probably missed this notification.

I've just realized that `permit_all_actions_except` is the same as `forbid_only_actions`. So what we need is an alias.

...Or I'm missing something 😅

**Comment by tagliala** [comment]
Friendly Bump

> I've just realized that `permit_all_actions_except` is the same as `forbid_only_actions`

@jacobperia can you please test and confirm?

**Comment by jacobperia** [comment]
> Friendly Bump
> 
> > I've just realized that `permit_all_actions_except` is the same as `forbid_only_actions`
> 
> @jacobperia can you please test and confirm?

@tagliala think I'm stupid lol. Somehow missed that method while going through the readme. Looks like it does the job! Apologize for wasting your time!

**Comment by tagliala** [comment]
No problem at all, I wanted to work on this feature myself :)

Closing here
